// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CaseClosed.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LogInAndGoToSmokeTests - Use 'LogInAndGoToSmokeTestsParams' to pass parameters into this method.
        /// </summary>
        public void LogInAndGoToSmokeTests()
        {
            #region Variable Declarations
            HtmlCustom uIHeadercommonCustom = this.UIMSNcomHotmailOutlookWindow.UIMSNcomHotmailOutlookDocument.UIHeadercommonCustom;
            BrowserWindow uIMSNcomHotmailOutlookWindow = this.UIMSNcomHotmailOutlookWindow;
            HtmlHyperlink uIUseanotheraccountHyperlink = this.UIMSNcomHotmailOutlookWindow.UISignintoCaseClosedWeDocument.UIUseanotheraccountHyperlink;
            HtmlEdit uIUseraccountEdit = this.UIMSNcomHotmailOutlookWindow.UISignintoCaseClosedWeDocument.UIUseraccountEdit;
            HtmlEdit uIPasswordEdit = this.UIMSNcomHotmailOutlookWindow.UISignintoCaseClosedWeDocument.UIPasswordEdit;
            HtmlSpan uISigninPane = this.UIMSNcomHotmailOutlookWindow.UISignintoCaseClosedWeDocument.UISigninPane;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            this.UIMSNcomHotmailOutlookWindow.LaunchUrl(new System.Uri(this.LogInAndGoToSmokeTestsParams.UIMSNcomHotmailOutlookWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'header-common' custom control at (1, 1)
            Mouse.Hover(uIHeadercommonCustom, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://casecloseddev.azurewebsites.net/smokeTests'
            uIMSNcomHotmailOutlookWindow.NavigateToUrl(new System.Uri(this.LogInAndGoToSmokeTestsParams.UIMSNcomHotmailOutlookWindowUrl1));

            // Click 'Use another account' link
            Mouse.Click(uIUseanotheraccountHyperlink, new Point(153, 42));

            // Type 'nkpatterson@caseclosed.onmicrosoft.com' in 'User account' text box
            uIUseraccountEdit.Text = this.LogInAndGoToSmokeTestsParams.UIUseraccountEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LogInAndGoToSmokeTestsParams.UIPasswordEditPassword;

            // Click 'Sign in' pane
            Mouse.Click(uISigninPane, new Point(35, 16));
        }
        
        /// <summary>
        /// ClickCreateTestButton
        /// </summary>
        public void ClickCreateTestButton()
        {
            #region Variable Declarations
            HtmlButton uICreateTestButton = this.UISmokeTestsMyASPNETApWindow.UISmokeTestsMyASPNETApDocument.UICreateTestButton;
            #endregion

            // Click 'Create Test' button
            Mouse.Click(uICreateTestButton, new Point(54, 14));
        }
        
        /// <summary>
        /// VerifySmokeTestWasSuccessful - Use 'VerifySmokeTestWasSuccessfulExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifySmokeTestWasSuccessful()
        {
            #region Variable Declarations
            HtmlDiv uISmokeTestwassuccessfPane = this.UISmokeTestsMyASPNETApWindow.UISmokeTestsMyASPNETApDocument.UISmokeTestwassuccessfPane;
            #endregion

            // Verify that the 'InnerText' property of 'Smoke Test was successful!' pane equals 'Smoke Test was successful! '
            Assert.AreEqual(this.VerifySmokeTestWasSuccessfulExpectedValues.UISmokeTestwassuccessfPaneInnerText, uISmokeTestwassuccessfPane.InnerText);
        }
        
        /// <summary>
        /// CloseBrowser
        /// </summary>
        public void CloseBrowser()
        {
            #region Variable Declarations
            BrowserWindow uISmokeTestsMyASPNETApWindow = this.UISmokeTestsMyASPNETApWindow;
            #endregion

            // Perform Close on Browser Window
            uISmokeTestsMyASPNETApWindow.Close();
        }
        
        #region Properties
        public virtual LogInAndGoToSmokeTestsParams LogInAndGoToSmokeTestsParams
        {
            get
            {
                if ((this.mLogInAndGoToSmokeTestsParams == null))
                {
                    this.mLogInAndGoToSmokeTestsParams = new LogInAndGoToSmokeTestsParams();
                }
                return this.mLogInAndGoToSmokeTestsParams;
            }
        }
        
        public virtual VerifySmokeTestWasSuccessfulExpectedValues VerifySmokeTestWasSuccessfulExpectedValues
        {
            get
            {
                if ((this.mVerifySmokeTestWasSuccessfulExpectedValues == null))
                {
                    this.mVerifySmokeTestWasSuccessfulExpectedValues = new VerifySmokeTestWasSuccessfulExpectedValues();
                }
                return this.mVerifySmokeTestWasSuccessfulExpectedValues;
            }
        }
        
        public UIMSNcomHotmailOutlookWindow UIMSNcomHotmailOutlookWindow
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookWindow == null))
                {
                    this.mUIMSNcomHotmailOutlookWindow = new UIMSNcomHotmailOutlookWindow();
                }
                return this.mUIMSNcomHotmailOutlookWindow;
            }
        }
        
        public UISmokeTestsMyASPNETApWindow UISmokeTestsMyASPNETApWindow
        {
            get
            {
                if ((this.mUISmokeTestsMyASPNETApWindow == null))
                {
                    this.mUISmokeTestsMyASPNETApWindow = new UISmokeTestsMyASPNETApWindow();
                }
                return this.mUISmokeTestsMyASPNETApWindow;
            }
        }
        #endregion
        
        #region Fields
        private LogInAndGoToSmokeTestsParams mLogInAndGoToSmokeTestsParams;
        
        private VerifySmokeTestWasSuccessfulExpectedValues mVerifySmokeTestWasSuccessfulExpectedValues;
        
        private UIMSNcomHotmailOutlookWindow mUIMSNcomHotmailOutlookWindow;
        
        private UISmokeTestsMyASPNETApWindow mUISmokeTestsMyASPNETApWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogInAndGoToSmokeTests'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LogInAndGoToSmokeTestsParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string UIMSNcomHotmailOutlookWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        
        /// <summary>
        /// Go to web page 'http://casecloseddev.azurewebsites.net/smokeTests'
        /// </summary>
        public string UIMSNcomHotmailOutlookWindowUrl1 = "http://casecloseddev.azurewebsites.net/smokeTests";
        
        /// <summary>
        /// Type 'nkpatterson@caseclosed.onmicrosoft.com' in 'User account' text box
        /// </summary>
        public string UIUseraccountEditText = "nkpatterson@caseclosed.onmicrosoft.com";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "ur05Cyd7vjJQuANVwT4FbSKiOv0ptwtr";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifySmokeTestWasSuccessful'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class VerifySmokeTestWasSuccessfulExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Smoke Test was successful!' pane equals 'Smoke Test was successful! '
        /// </summary>
        public string UISmokeTestwassuccessfPaneInnerText = "Smoke Test was successful! ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookWindow : BrowserWindow
    {
        
        public UIMSNcomHotmailOutlookWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            this.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMSNcomHotmailOutlookDocument UIMSNcomHotmailOutlookDocument
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookDocument == null))
                {
                    this.mUIMSNcomHotmailOutlookDocument = new UIMSNcomHotmailOutlookDocument(this);
                }
                return this.mUIMSNcomHotmailOutlookDocument;
            }
        }
        
        public UISignintoCaseClosedWeDocument UISignintoCaseClosedWeDocument
        {
            get
            {
                if ((this.mUISignintoCaseClosedWeDocument == null))
                {
                    this.mUISignintoCaseClosedWeDocument = new UISignintoCaseClosedWeDocument(this);
                }
                return this.mUISignintoCaseClosedWeDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMSNcomHotmailOutlookDocument mUIMSNcomHotmailOutlookDocument;
        
        private UISignintoCaseClosedWeDocument mUISignintoCaseClosedWeDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookDocument : HtmlDocument
    {
        
        public UIMSNcomHotmailOutlookDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/?ocid=iehp";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIHeadercommonCustom
        {
            get
            {
                if ((this.mUIHeadercommonCustom == null))
                {
                    this.mUIHeadercommonCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIHeadercommonCustom.SearchProperties["TagName"] = "HEADER";
                    this.mUIHeadercommonCustom.SearchProperties["Id"] = "header-common";
                    this.mUIHeadercommonCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIHeadercommonCustom.FilterProperties["Class"] = "no-overlay";
                    this.mUIHeadercommonCustom.FilterProperties["ControlDefinition"] = "class=\"no-overlay\" id=\"header-common\" ro";
                    this.mUIHeadercommonCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIHeadercommonCustom.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUIHeadercommonCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIHeadercommonCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISignintoCaseClosedWeDocument : HtmlDocument
    {
        
        public UISignintoCaseClosedWeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in to CaseClosed.Web.dev";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/3169cc1d-dcd7-4839-9aec-723163760fb6/oauth2/authorize";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://login.microsoftonline.com/3169cc1d-dcd7-4839-9aec-723163760fb6/oauth2/authorize?client_id=8da7e59c-da4a-4030-b34e-58ed5095e268&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3duBQsZnvitwetE9MACPKWrTDo_hGh_zGKqyYC8uMJ5KQ_njJTbTEatq_gdWS7aOg4p8pYjHbGjgKNYVMQz1vRu_jxmed_Ng2eq87a0ARMR22KYV89l-XeFRbEbSHO0fOWvvNU1_4juG5aE31WZ-RskHkBBKBoEx2ryfxkm1zcZ1g&nonce=635821100087539720.YTc3ZGU4YzItMmQ0NS00Y2MxLWIwOTMtOTIyODVjZDc3ODI3MTJmZTU1MmYtNTAyZi00MTRkLTgzYjUtZmIxNDI4YjExMjMy";
            this.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIUseanotheraccountHyperlink
        {
            get
            {
                if ((this.mUIUseanotheraccountHyperlink == null))
                {
                    this.mUIUseanotheraccountHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIUseanotheraccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "use_another_account_link";
                    this.mUIUseanotheraccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIUseanotheraccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIUseanotheraccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " \r\nUse another account ";
                    this.mUIUseanotheraccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIUseanotheraccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIUseanotheraccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#";
                    this.mUIUseanotheraccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "tile_link tooltip";
                    this.mUIUseanotheraccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabindex=\"1\" class=\"tile_link tooltip\" i";
                    this.mUIUseanotheraccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIUseanotheraccountHyperlink.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUIUseanotheraccountHyperlink;
            }
        }
        
        public HtmlEdit UIUseraccountEdit
        {
            get
            {
                if ((this.mUIUseraccountEdit == null))
                {
                    this.mUIUseraccountEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUseraccountEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_userid_inputtext";
                    this.mUIUseraccountEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User account";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required email field normaltext";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" tabindex=\"1\" class=\"login_t";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUseraccountEdit.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUIUseraccountEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_password_inputtext";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required field normaltext";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" tabindex=\"2\" class=\"login_";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlSpan UISigninPane
        {
            get
            {
                if ((this.mUISigninPane == null))
                {
                    this.mUISigninPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cred_sign_in_button";
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign in";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "button normaltext cred_sign_in_button refresh_domain_state control-button button-" +
                        "two button_primary";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"11\" class=\"button normaltext cred_sign_in_button refresh_domain_state c" +
                        "ontrol-button button-two button_primary\" id=\"cred_sign_in_button\" role=\"button\" " +
                        "style=\"opacity: 1;\"";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUISigninPane.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUISigninPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIUseanotheraccountHyperlink;
        
        private HtmlEdit mUIUseraccountEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlSpan mUISigninPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISmokeTestsMyASPNETApWindow : BrowserWindow
    {
        
        public UISmokeTestsMyASPNETApWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Smoke Tests - My ASP.NET Application";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISmokeTestsMyASPNETApDocument UISmokeTestsMyASPNETApDocument
        {
            get
            {
                if ((this.mUISmokeTestsMyASPNETApDocument == null))
                {
                    this.mUISmokeTestsMyASPNETApDocument = new UISmokeTestsMyASPNETApDocument(this);
                }
                return this.mUISmokeTestsMyASPNETApDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISmokeTestsMyASPNETApDocument mUISmokeTestsMyASPNETApDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISmokeTestsMyASPNETApDocument : HtmlDocument
    {
        
        public UISmokeTestsMyASPNETApDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Smoke Tests - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/smokeTests";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://casecloseddev.azurewebsites.net/smokeTests";
            this.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlButton UICreateTestButton
        {
            get
            {
                if ((this.mUICreateTestButton == null))
                {
                    this.mUICreateTestButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Create Test";
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\"";
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUICreateTestButton.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
                    #endregion
                }
                return this.mUICreateTestButton;
            }
        }
        
        public HtmlDiv UISmokeTestwassuccessfPane
        {
            get
            {
                if ((this.mUISmokeTestwassuccessfPane == null))
                {
                    this.mUISmokeTestwassuccessfPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUISmokeTestwassuccessfPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUISmokeTestwassuccessfPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Smoke Test was successful! ";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\"";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
                    this.mUISmokeTestwassuccessfPane.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
                    #endregion
                }
                return this.mUISmokeTestwassuccessfPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUICreateTestButton;
        
        private HtmlDiv mUISmokeTestwassuccessfPane;
        #endregion
    }
}
