// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CaseClosed.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ClickCreateTestButton
        /// </summary>
        public void ClickCreateTestButton()
        {
            #region Variable Declarations
            HtmlButton uICreateTestButton = this.UISmokeTestsMyASPNETApWindow.UISmokeTestsMyASPNETApDocument.UICreateTestButton;
            #endregion

            // Click 'Create Test' button
            Mouse.Click(uICreateTestButton, new Point(59, 14));
        }
        
        /// <summary>
        /// CloseBrowser
        /// </summary>
        public void CloseBrowser()
        {
            #region Variable Declarations
            BrowserWindow uISmokeTestsMyASPNETApWindow = this.UISmokeTestsMyASPNETApWindow;
            #endregion

            // Perform Close on Browser Window
            uISmokeTestsMyASPNETApWindow.Close();
        }
        
        /// <summary>
        /// LogInAndGoToSmokeTests - Use 'LogInAndGoToSmokeTestsParams' to pass parameters into this method.
        /// </summary>
        public void LogInAndGoToSmokeTests()
        {
            #region Variable Declarations
            BrowserWindow uIInPrivateInternetExpWindow1 = this.UIInPrivateInternetExpWindow;
            HtmlEdit uIUseraccountEdit = this.UIInPrivateInternetExpWindow.UISignintoCaseClosedWeDocument.UIUseraccountEdit;
            HtmlEdit uIPasswordEdit = this.UIInPrivateInternetExpWindow.UISignintoCaseClosedWeDocument.UIPasswordEdit;
            HtmlSpan uISigninPane = this.UIInPrivateInternetExpWindow.UISignintoCaseClosedWeDocument.UISigninPane;
            #endregion

            // Launch '%ProgramW6432%\Internet Explorer\iexplore.exe' with arguments '-private'
            ApplicationUnderTest uIInPrivateInternetExpWindow = ApplicationUnderTest.Launch(this.LogInAndGoToSmokeTestsParams.UIInPrivateInternetExpWindowExePath, this.LogInAndGoToSmokeTestsParams.UIInPrivateInternetExpWindowAlternateExePath, "-private");

            // Go to web page 'http://casecloseddev.azurewebsites.net/smokeTests'
            uIInPrivateInternetExpWindow1.NavigateToUrl(new System.Uri(this.LogInAndGoToSmokeTestsParams.UIInPrivateInternetExpWindowUrl));

            // Type 'nkpatterson@caseclosed.onmicrosoft.com' in 'User account' text box
            uIUseraccountEdit.Text = this.LogInAndGoToSmokeTestsParams.UIUseraccountEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LogInAndGoToSmokeTestsParams.UIPasswordEditPassword;

            // Click 'Sign in' pane
            Mouse.Click(uISigninPane, new Point(37, 20));
        }
        
        /// <summary>
        /// VerifySmokeTestWasSuccessful - Use 'VerifySmokeTestWasSuccessfulExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifySmokeTestWasSuccessful()
        {
            #region Variable Declarations
            HtmlDiv uISmokeTestwassuccessfPane = this.UISmokeTestsMyASPNETApWindow.UISmokeTestsMyASPNETApDocument.UISmokeTestwassuccessfPane;
            #endregion

            // Verify that the 'InnerText' property of 'Smoke Test was successful!' pane equals 'Smoke Test was successful! '
            Assert.AreEqual(this.VerifySmokeTestWasSuccessfulExpectedValues.UISmokeTestwassuccessfPaneInnerText, uISmokeTestwassuccessfPane.InnerText);
        }
        
        #region Properties
        public virtual LogInAndGoToSmokeTestsParams LogInAndGoToSmokeTestsParams
        {
            get
            {
                if ((this.mLogInAndGoToSmokeTestsParams == null))
                {
                    this.mLogInAndGoToSmokeTestsParams = new LogInAndGoToSmokeTestsParams();
                }
                return this.mLogInAndGoToSmokeTestsParams;
            }
        }
        
        public virtual VerifySmokeTestWasSuccessfulExpectedValues VerifySmokeTestWasSuccessfulExpectedValues
        {
            get
            {
                if ((this.mVerifySmokeTestWasSuccessfulExpectedValues == null))
                {
                    this.mVerifySmokeTestWasSuccessfulExpectedValues = new VerifySmokeTestWasSuccessfulExpectedValues();
                }
                return this.mVerifySmokeTestWasSuccessfulExpectedValues;
            }
        }
        
        public UIInPrivateInternetExpWindow UIInPrivateInternetExpWindow
        {
            get
            {
                if ((this.mUIInPrivateInternetExpWindow == null))
                {
                    this.mUIInPrivateInternetExpWindow = new UIInPrivateInternetExpWindow();
                }
                return this.mUIInPrivateInternetExpWindow;
            }
        }
        
        public UISmokeTestsMyASPNETApWindow UISmokeTestsMyASPNETApWindow
        {
            get
            {
                if ((this.mUISmokeTestsMyASPNETApWindow == null))
                {
                    this.mUISmokeTestsMyASPNETApWindow = new UISmokeTestsMyASPNETApWindow();
                }
                return this.mUISmokeTestsMyASPNETApWindow;
            }
        }
        #endregion
        
        #region Fields
        private LogInAndGoToSmokeTestsParams mLogInAndGoToSmokeTestsParams;
        
        private VerifySmokeTestWasSuccessfulExpectedValues mVerifySmokeTestWasSuccessfulExpectedValues;
        
        private UIInPrivateInternetExpWindow mUIInPrivateInternetExpWindow;
        
        private UISmokeTestsMyASPNETApWindow mUISmokeTestsMyASPNETApWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogInAndGoToSmokeTests'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LogInAndGoToSmokeTestsParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramW6432%\Internet Explorer\iexplore.exe' with arguments '-private'
        /// </summary>
        public string UIInPrivateInternetExpWindowExePath = "C:\\Program Files\\Internet Explorer\\iexplore.exe";
        
        /// <summary>
        /// Launch '%ProgramW6432%\Internet Explorer\iexplore.exe' with arguments '-private'
        /// </summary>
        public string UIInPrivateInternetExpWindowAlternateExePath = "%ProgramW6432%\\Internet Explorer\\iexplore.exe";
        
        /// <summary>
        /// Go to web page 'http://casecloseddev.azurewebsites.net/smokeTests'
        /// </summary>
        public string UIInPrivateInternetExpWindowUrl = "http://casecloseddev.azurewebsites.net/smokeTests";
        
        /// <summary>
        /// Type 'nkpatterson@caseclosed.onmicrosoft.com' in 'User account' text box
        /// </summary>
        public string UIUseraccountEditText = "nkpatterson@caseclosed.onmicrosoft.com";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "ur05Cyd7vjJQuANVwT4FbSKiOv0ptwtr";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifySmokeTestWasSuccessful'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class VerifySmokeTestWasSuccessfulExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Smoke Test was successful!' pane equals 'Smoke Test was successful! '
        /// </summary>
        public string UISmokeTestwassuccessfPaneInnerText = "Smoke Test was successful! ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIInPrivateInternetExpWindow : BrowserWindow
    {
        
        public UIInPrivateInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "InPrivate";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("InPrivate");
            this.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISignintoCaseClosedWeDocument UISignintoCaseClosedWeDocument
        {
            get
            {
                if ((this.mUISignintoCaseClosedWeDocument == null))
                {
                    this.mUISignintoCaseClosedWeDocument = new UISignintoCaseClosedWeDocument(this);
                }
                return this.mUISignintoCaseClosedWeDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISignintoCaseClosedWeDocument mUISignintoCaseClosedWeDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISignintoCaseClosedWeDocument : HtmlDocument
    {
        
        public UISignintoCaseClosedWeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in to CaseClosed.Web.dev";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/3169cc1d-dcd7-4839-9aec-723163760fb6/oauth2/authorize";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://login.microsoftonline.com/3169cc1d-dcd7-4839-9aec-723163760fb6/oauth2/authorize?client_id=8da7e59c-da4a-4030-b34e-58ed5095e268&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3ddL7d69LrW4_ieQPky3eGtYO-cr-Ja6_cDkiC_1wlhLi6ocD44jCRV_85rho0RTFD-MTpzBwS5wVSxlD6Enp6NWT211buo9xPbEr8sORLO0MUjDItK0Fh9ZzwJFd_MCVMGi0DGnfN-UgAyLMSfcdB9HuIdjo00Xkjswne8AcUhyE&nonce=635821139895550998.ODE5N2E3YjctNjAxMC00ZjdkLWJlOWUtOWIzZTlkOGZmZjZiNjBjMjEwYmEtMzZmMy00ZDdlLTlhZTctN2U1ZGU1N2ViMWRk";
            this.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUseraccountEdit
        {
            get
            {
                if ((this.mUIUseraccountEdit == null))
                {
                    this.mUIUseraccountEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUseraccountEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_userid_inputtext";
                    this.mUIUseraccountEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User account";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required email field normaltext";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" tabindex=\"1\" class=\"login_t";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUseraccountEdit.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUIUseraccountEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_password_inputtext";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required field normaltext";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" tabindex=\"2\" class=\"login_";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlSpan UISigninPane
        {
            get
            {
                if ((this.mUISigninPane == null))
                {
                    this.mUISigninPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cred_sign_in_button";
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign in";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "button normaltext cred_sign_in_button refresh_domain_state control-button button-" +
                        "two button_primary";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"11\" class=\"button normaltext cred_sign_in_button refresh_domain_state c" +
                        "ontrol-button button-two button_primary\" id=\"cred_sign_in_button\" role=\"button\" " +
                        "style=\"opacity: 1;\"";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUISigninPane.WindowTitles.Add("Sign in to CaseClosed.Web.dev");
                    #endregion
                }
                return this.mUISigninPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUseraccountEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlSpan mUISigninPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISmokeTestsMyASPNETApWindow : BrowserWindow
    {
        
        public UISmokeTestsMyASPNETApWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Smoke Tests - My ASP.NET Application";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISmokeTestsMyASPNETApDocument UISmokeTestsMyASPNETApDocument
        {
            get
            {
                if ((this.mUISmokeTestsMyASPNETApDocument == null))
                {
                    this.mUISmokeTestsMyASPNETApDocument = new UISmokeTestsMyASPNETApDocument(this);
                }
                return this.mUISmokeTestsMyASPNETApDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISmokeTestsMyASPNETApDocument mUISmokeTestsMyASPNETApDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISmokeTestsMyASPNETApDocument : HtmlDocument
    {
        
        public UISmokeTestsMyASPNETApDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Smoke Tests - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/smokeTests";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://casecloseddev.azurewebsites.net/smokeTests";
            this.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlButton UICreateTestButton
        {
            get
            {
                if ((this.mUICreateTestButton == null))
                {
                    this.mUICreateTestButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnCreateTest";
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.Name] = "";
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Create Test";
                    this.mUICreateTestButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\"";
                    this.mUICreateTestButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUICreateTestButton.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
                    #endregion
                }
                return this.mUICreateTestButton;
            }
        }
        
        public HtmlDiv UISmokeTestwassuccessfPane
        {
            get
            {
                if ((this.mUISmokeTestwassuccessfPane == null))
                {
                    this.mUISmokeTestwassuccessfPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUISmokeTestwassuccessfPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "flash";
                    this.mUISmokeTestwassuccessfPane.SearchProperties[HtmlDiv.PropertyNames.Name] = "";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Smoke Test was successful! ";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\"";
                    this.mUISmokeTestwassuccessfPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
                    this.mUISmokeTestwassuccessfPane.WindowTitles.Add("Smoke Tests - My ASP.NET Application");
                    #endregion
                }
                return this.mUISmokeTestwassuccessfPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUICreateTestButton;
        
        private HtmlDiv mUISmokeTestwassuccessfPane;
        #endregion
    }
}
